### ISSUE TITLE
请教一直显示 tools is not defined

### ISSUE THREAD

**Issue by kkcao** [miiwu/sspanel.soulsign#7]
萌新求教

按图填写好参数之后 一直提示 ReferenceError: tools is not defiend

请问是否填写的格式或者内容不对?

![捕获](https://user-images.githubusercontent.com/38519034/93328894-f2087700-f84e-11ea-8b2d-14c1daccd887.PNG)

另外请问http://www.52taozx.com的 plugin.php?id=mpage_sign:sign 是否支持自动签到?

**Comment by miiwu** [comment]
> 按图填写好参数之后 一直提示 ReferenceError: tools is not defiend

你的 soulsign 版本是什么呀？
非最新版兼容性可能会出问题；

建议去主仓库下载最新版试试。

> 请问是否填写的格式或者内容不对？

格式没问题。
测试了 [`k8sj.com`](http://www.k8sj.com/plugin.php?id=dsu_paulsign:sign) 是 `discuz` 的默认情况，可自动签到。
除了域名，一般其他选项不需要填写。

> 另外请问 [http://www.52taozx.com 的](http://www.52taozx.com%E7%9A%84) plugin.php?id=mpage_sign:sign 是否支持自动签到？

看了一下 [`52taozx.com`](http://www.52taozx.com/mpage_sign-sign.html) 应该是新的情况，看着非常类似 `discuz.dc` 的情况，原则上可以通过修改 `xx路径` 参数兼容；
然而由于本人写东西不动脑子，这里出现了问题；

麻烦把 `discuz.dc` 复制一个副本出来，
脚本内容，做如下改变：
```javascript
    ...
    path: {
        log_in: ["plugin.php?id=mpage_sign:sign"], // 登录的
        sign_in: ["plugin.php?id=mpage_sign:sign&inajax=1"], // 签到的
    }, // 网址主机的目录
    ...
```
脚本参数：
`域名` 填写 `http://www.52taozx.com`；
`在线关键字` 填写 `退出` 应该可以解决；

我仅测试了手动签到完成后，运行本脚本的反馈情况，如果无法签到，请继续反馈。

- - -

对此非常抱歉，我现在可能不能及时修复掉这些问题。

**Comment by kkcao** [comment]
非常感谢回复和帮助!

原本使用的是Firefox 版本 换成Chrome 版本就可以了

修改后mpage的 签到失败 错误日志

{
"domain":
"www.52taozx.com",

"url":
"http://www.52taozx.com/plugin.php?id=mpage_sign:sign",

"errno":
true,

"message":
"签到失败",

"log": [
{...}, 6 items
"<?xml version="1.0" encoding="gbk"?> <root><![CDATA[请选择一个心情<script type="text/javascript" reload="1">if(typeof errorhandle_signin=='function') {errorhandle_signin('请选择一个心情', {});}</script>]]></root>",

"Cannot read property 'match' of undefined"

]

}

**Comment by miiwu** [comment]
> "if (typeof errorhandle_signin=='function') {errorhandle_signin (' 请选择一个心情 ', {});}]]>",

谢谢反馈，
看得出来是推送时的携带参数问题。

请做如下修改：
```javascript
    ...
    `formhash=${formhash}&signsubmit=yes&handlekey=sign&moodid=1&content=${say}`
    ...
```

本地测试可以自动签到成功；
若有问题，烦请继续反馈呀。

**Comment by kkcao** [comment]
签到成功了 非常感谢您的脚本和帮助!
